### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by ferroao** [d10r/kindle-fetch#2]
As a suggestion, state which version of node.js is recommended in readme.

**Comment by d10r** [comment]
To be honest, I don't remember. I'm pretty sure node v8 works, probably v6 too. Which version did you try? And did it work?

**Comment by ferroao** [comment]
I think I tried 11 and 8, with 8 worked.

**Comment by d10r** [comment]
Thx for info, I added it to the README.  
Seems indeed to not work with anything never than v8.
