### ISSUE TITLE
imageData not set

### ISSUE THREAD

**Issue by AGuyCoding** [d10r/kindle-fetch#4]
the key "imageData" ist not set anymore, what makes this script useless sadly, right?

**Comment by srghma** [comment]
what is "imageData"?

**Comment by iongradea** [comment]
@benjaminadrom , The script works fine, I just made it work tonight !  
Have a look at the issue I opened and close to check the different versions you have for chrome and node.  
Here the issue : https://github.com/d10r/kindle-fetch/issues/9.  
If you have any other issue, feel free to ask !
