### ISSUE TITLE
Warning Deprecation - not all books retrieved 

### ISSUE THREAD

**Issue by etanus11** [d10r/kindle-fetch#6]
When running the command ( ./main.js -f ~/.config/chromium/Default/databases/https_read.amazon.com_0/2 
) I get 
(node:14040) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
fs.js:113
      throw err;  // Forgot a callback but don't know where? Use NODE_DEBUG=fs
      ^
Error: EMFILE: too many open files, open 'Black-Beauty.html'
I am working on Ubuntu 18.04..
Renate

**Comment by etanus11** [comment]
In

**Comment by d10r** [comment]
should now work: https://github.com/d10r/kindle-fetch/pull/8
